Добавляем документацию о скриптах
Кроме этого git-export сделан менее опасным. Убрана директория
/etc/postgresql, которая создаётся во время установки.

diff --git a/git-export b/git-export
--- a/git-export
+++ b/git-export
@@ -1,9 +1,9 @@
 #!/bin/sh
 
-if [ -e $1 ]; then
-    echo "Error:Could not export to $1, directory or file exsist.";
-    exit 1;
-fi
+#if [ -e $1 ]; then
+#    echo "Error:Could not export to $1, directory or file exsist.";
+#    exit 1;
+#fi
 
 mkdir -p $1
 git archive master | tar -x -C $1
